// <auto-generated />
using System;
using Autoship.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autoship.Migrations
{
    [DbContext(typeof(AutoshipContext))]
    [Migration("20200901052553_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("Autoship.Models.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usertype")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "superuser",
                            Username = "superuser",
                            Usertype = 0
                        },
                        new
                        {
                            Id = 2,
                            Password = "admin",
                            Username = "admin",
                            Usertype = 1
                        },
                        new
                        {
                            Id = 3,
                            Password = "corriere",
                            Username = "corriere",
                            Usertype = 2
                        },
                        new
                        {
                            Id = 4,
                            Password = "user",
                            Username = "user",
                            Usertype = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
